(package "haxe-mode"
         "0.3.3"
         "Major mode for editing Haxe files")

(website-url "https://github.com/emacsorphanage/haxe-mode")
(keywords "")

(package-file "haxe-mode.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")
(source "melpa")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
